### ISSUE TITLE
Missing data for Canada

### ISSUE THREAD

**Issue by craigplusplus** [zbraniecki/covid19-timeseries#21]
It seems like the last data import omitted Canada, as it doesn't show up in the list of regions as of March 26.

**Comment by zbraniecki** [comment]
I see https://zbraniecki.github.io/covid19-timeseries/?tax=country&tax=state&region=CAN_Quebec&region=CAN_Quebec&region=CAN_Ontario&region=CAN_British+Columbia&region=CAN_Alberta&region=CAN_Saskatchewan&region=CAN_Nova+Scotia&region=CAN_Newfoundland+and+Labrador&region=CAN_New+Brunswick&region=CAN_Manitoba&region=CAN_Prince+Edward+Island&region=CAN_Yukon&region=CAN_Total&region=CAN_Quebec&region=CAN_Ontario&region=CAN_British+Columbia&region=CAN_Alberta&region=CAN_Saskatchewan&region=CAN_Nova+Scotia&region=CAN_Newfoundland+and+Labrador&region=CAN_New+Brunswick&region=CAN_Manitoba&region=CAN_Prince+Edward+Island&region=CAN_Yukon&type=cases - is that what you're looking for?

**Comment by craigplusplus** [comment]
It is, thank you! Up until a few days ago Canada‘s total values showed up with “Countries” selected. Now it only seems to show up when “State” is selected, which was why I couldn’t find anything. A little confusing, but I’m glad to have the data!

**Comment by zbraniecki** [comment]
Ah, yes, it's a bug - I reported it upstream as https://github.com/lazd/coronadatascraper/issues/405 - will keep this open until the upstream bug gets fixed and we pull updated data. Thank you!

**Comment by zbraniecki** [comment]
Fixed upstream by https://github.com/covidatlas/coronadatascraper/commit/5bb7fcc23e864922db95b3f9e8302724ab3e5821
